### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Zathrox** [BinaryQuantumSoul/BinaryMod#2]
How are you registering your features? 1.16.5

I've stumbled upon your github and out of all the world gen, biome and feature generation, you seem to have the cleanest setup for it and after following a similar suit for my mod, i'm having the issues with my custom features being missing at the generation of the biome! 

Do you have any idea how to get around this? but I also noted you don't seem to register your features so was also curious on that!

**Comment by Zathrox** [comment]
I managed to find a solution for my features! Thanks! Even though you didn't reply, your code is pretty clean and readable, so it helped either way :D

**Comment by BinaryQuantumSoul** [comment]
> I managed to find a solution for my features! Thanks! Even though you didn't reply, your code is pretty clean and readable, so it helped either way :D

Yup sorry I don't have as much time as before for these. I'm glad my code helped you :)
